spring:
    datasource:
        url: jdbc:postgresql://3.37.244.96:5432/kotlindb
        username: master_user_01
        password: master
        driverClassName: org.postgresql.Driver


#spring.datasource.firstdb.jdbc-url=jdbc:postgresql://3.37.244.96:5432/kotlindb
#spring.datasource.firstdb.username=master_user_01
#spring.datasource.firstdb.password=master
#spring.datasource.firstdb.driver-class-name=org.postgresql.Driver

#spring:
#    datasource:
#        url: jdbc:postgresql://3.37.244.96:5432/testdb
#        username:testuser
#        password:testuser1!
#        driverClassName: org.postgresql.Driver
#    jpa:
#        properties:
#            hibernate:
#                temp:
#                    use_jdbc_metadata_defaults: false
#                show_sql: true
#        generate-ddl: true
#        hibernate:
#            ddl-auto: update
#            generate-ddl: true
#            properties:
#            temp:
#                use_jdbc_metadata_defaults: false